### Products index action
GET http://localhost:3000/products.json

### Products show action
GET http://localhost:3000/products/4.json

### Products create action
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test name",
  "price": "test price", 
  "description": "test"
}

### Products update action
PATCH http://localhost:3000/products/4.json
Content-Type: application/json

{
  "price": 9.99
}

### Products delete action
DELETE http://localhost:3000/products/5




### Suppliers index action
GET http://localhost:3000/suppliers.json

### Suppliers show action
GET http://localhost:3000/suppliers/3.json

### Suppliers create action
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "test name",
  "email": "test email", 
  "phone_number": "test phone_number"
 
}

### Suppliers update action
PATCH http://localhost:3000/suppliers/3.json
Content-Type: application/json

{
  "name": "Barnes and Noble Classics"
}

### Suppliers delete action
DELETE http://localhost:3000/suppliers/4
